name: basicWorkflow
on: workflow_dispatch
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: say-hello
      run: echo "Hi There!!"
    - name: say-goodbye
      run: echo "Goodbye There!!"
